spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jngvarr/RemoteConfig
          default-label: main
#          password: ${GITHUB_TOKEN}
          password:
          username: jngvarr
  application:
    name: config-server
server:
  port: 8888

logging:
  level:
    org.springframework.cloud.config: DEBUG
