spring:
  application:
    name:
      TGBot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://62.76.142.52:5432/tgbotdb
    username: tgbot
    password: tgbotpass
    driver-class-name: org.postgresql.Driver
logging:
  level:
    ru.jngvarr: DEBUG
telegram:
  bot:
    name: PTO_ACKYE_bot
    token: 7887488572:AAHU1Vb-8NLc3ug-hV6Ju8YNnpFXE24iV2Q
    owner: 199867696
