spring:
  application:
    name:
      TGBot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://62.76.142.52:5432/tgbotdb
    username: tgbot
    password: tgbotpass
#    driver-class-name:
#      com:
#        postgresql.cj.jdbc.driver
logging:
  level:
    ru.jngvarr: DEBUG
telegram:
  bot:
    name: PTO_ACKYE_bot
    token: 7887488572:AAHUe9YUZEGR60nGjYUyD-oYLsf_8vmJwno