set search_path = ackye;
drop schema ackye cascade ;
create schema IF NOT EXISTS ackye;

create table  if not exists regions
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table regions
    owner to ackye;

insert into regions (name)
values ('Алтайский край');

create table structural_subdivisions
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255) not null,
    region_id bigint       not null
        constraint fk_structural_subdivisions_region_id
            references regions (id)
);

alter table structural_subdivisions
    owner to ackye;


insert into structural_subdivisions (id, name, region_id)
values (1, 'ЭЭЛ-4', 1);

create table power_supply_enterprises
(
    id                        bigint generated by default as identity
        primary key,
    name                      varchar(255) not null,
    structural_subdivision_id bigint       not null
        constraint fk_power_supply_enterprises_structural_subdivisions_id
            references structural_subdivisions
);

alter table power_supply_enterprises
    owner to ackye;

insert into power_supply_enterprises (id, name, structural_subdivision_id)
values (1, 'ЭЧ-10', 1);


create table power_supply_districts
(
    id                         bigint generated by default as identity
        primary key,
    name                       varchar(255) not null,
    power_supply_enterprise_id bigint       not null
        constraint fk_power_supply_districts_power_supply_enterprises_id
            references power_supply_enterprises
);

alter table power_supply_districts
    owner to ackye;

insert into power_supply_districts (id, name, power_supply_enterprise_id)
values (1, 'ЭЧС-404', 1);

create table stations
(
    id                       bigint generated by default as identity
        primary key,
    name                     varchar(255) not null,
    power_supply_district_id bigint       not null
        constraint fkc4frgj9bi77epnkn06nhgykmk
            references power_supply_districts
);

alter table stations
    owner to ackye;

create table substations
(
    id         bigint generated by default as identity
        primary key,
    name       varchar(255) not null,
    station_id bigint       not null
        constraint fkddfu4u28x0aq6o6dr7g2u57il
            references stations
);

alter table substations
    owner to ackye;

create table if not exists iiks
(
    id                     bigint       not null
        primary key,
    connection             varchar(255),
    installation_date      date,
    meter_placement        varchar(255),
    metering_point_address varchar(255) not null,
    name                   varchar(255) not null,
    iik_state_id           bigint
        constraint uktn5q8b1pghc934dyhkbf96625
            unique
        constraint fk472jldd35f9ibwayyld05sgwb
            references iik_states,
    meter_id               bigint       not null
        constraint ukso27tjay3ga90jr5jec24ibav
            unique
        constraint fkpojdau8vhkcjrb1650htuxa1x
            references meters,
    substation_id          bigint       not null
        constraint fkfjo9lniwey6loihtcmjrtqc0w
            references substations
);





alter table iiks
    owner to ackye;


create table meters
(
    id           bigint generated by default as identity
        primary key,
    meter_model  varchar(255) not null,
    meter_number varchar(255) not null,
    dc_id        bigint       not null
        constraint fkl6a7nsrl43by4f5h7hida1yxn
            references dcs
);

alter table meters
    owner to ackye;

create table iik_states
(
    id                      bigint       not null
        primary key,
    dispatcher_task         varchar(255),
    current_state           varchar(255) not null,
    gorizont_status         varchar(255) not null,
    last_communication_date date         not null,
    not_or_not_not          varchar(255) not null,
    team_report             varchar(255)
);

alter table iik_states
    owner to ackye;


create table dc_complexes
(
    id                bigint generated by default as identity
        primary key,
    bus_section       integer not null,
    installation_date date,
    substation_id     bigint  not null
        constraint fk4gfd1ieobm9adxk22feegslll
            references substations
);

alter table dc_complexes
    owner to ackye;

create table dcs
(
    id               bigint generated by default as identity
        primary key,
    dc_model         varchar(255),
    dc_number        varchar(255) not null,
    manufacture_date date,
    dc_complex_id    bigint       not null
        constraint ukaavtd9k1txdfrbsfypfa59c8h
            unique
        constraint fkpq3rf4e6qjnaiul92kwxld7u2
            references dc_complexes
);

alter table dcs
    owner to ackye;

create table ivke_states
(
    id                   bigint       not null
        primary key,
    dispatcher_task      varchar(255),
    current_state        varchar(255) not null,
    last_connection_date date         not null,
    team_report          varchar(255)
);

alter table ivke_states
    owner to ackye;


insert into iiks (connection, meter_placement, installation_date)
values (connection,)

insert into visits (date, start_time, service_id, client_id, master_id)
values ('2006-12-11', '12:00:01', 1, 2, 3),
       ('2006-12-12', '12:00:02', 1, 1, 1),
       ('2006-12-13', '12:00:03', 1, 1, 2);

insert into clients (first_name, last_name, contact, dob)
values ('Иван', 'Иванов', '+79998887766', '2001-01-01'),
       ('Пётр', 'Петров', '+79995554433', '2002-02-02');

insert into services (title, price, duration, description)
values ('Мужская стрижка', 299, '20', 'любая стрижка'),
       ('Женская стрижка', 299, '60', 'любая стрижка, кроме "каре"'),
       ('Простое окрашивание', 1000, '120', 'короткие волосы');

insert into employees (first_name, last_name, contact, dob, function)
values ('Светлана', 'Кукушкина', '+75598887766', '2001-08-07', 'HAIRDRESSER'),
       ('Евгения', 'Матрёшкина', '+79445554411', '2002-05-19', 'NAILMASTER'),
       ('Инна', 'Поварёжкина', '+79995554433', '2003-07-13', 'ADMIN'),
       ('Екатерина', 'Щеглова', '+79545554412', '2002-05-19', 'CLEANING');

insert into consumables (title, unit, price)
values ('Краска', 'Штука', 255.7),
       ('Полотенце', 'Штука', 10),
       ('Простыня', 'Штука', 20),
       ('Крем для солярия', 'Штука', 120),
       ('Оксидант1', 'Бутылка', 179.9),
       ('Оксидант2', 'Бутылка', 189.9),
       ('Оксидант3', 'Бутылка', 199.9);



SELECT
    mp.id AS metering_point_id,
--     r.id AS region_id,
    r.name AS region_name,
    ss.name AS structural_subdivision_name,
    pse.name AS power_supply_enterprise_name,
    psd.name AS power_supply_district_name,
    st.name AS station_name,
    s.name AS substation_name,
    mp.name AS metering_point_name,
    mp.metering_point_address,
--     s.id AS substation_id,
--     st.id AS station_id,
--     psd.id AS power_supply_district_id,
--     pse.id AS power_supply_enterprise_id,
--     ss.id AS structural_subdivision_id,
--     mp.connection,
--     mp.meter_placement,
--     m.id AS meter_id,
    m.meter_model,
    m.meter_number,
    dc.dc_model,
    dc.dc_number,
    dc.bus_section,
--     m.dc_id,
--     dc.id AS data_concentrator_id,
    mp.installation_date AS mp_installation_date,
    dc.installation_date AS dc_installation_date
--     dc.manufacture_date
FROM
    metering_points mp
        LEFT JOIN
    meters m ON mp.id = m.metering_point_id
        LEFT JOIN
    data_concentrators dc ON dc.id = m.dc_id
        LEFT JOIN
    substations s ON mp.substation_id = s.id
        LEFT JOIN
    stations st ON s.station_id = st.id
        LEFT JOIN
    power_supply_districts psd ON st.power_supply_district_id = psd.id
        LEFT JOIN
    power_supply_enterprises pse ON psd.power_supply_enterprise_id = pse.id
        LEFT JOIN
    structural_subdivisions ss ON pse.structural_subdivision_id = ss.id
        LEFT JOIN
    regions r ON st.id = r.id;