spring:
  cloud:
      openfeign:
        client:
          config:
            clients:
              url: http://localhost:8081
            staff:
              url: http://localhost:8084
            services:
              url: http://localhost:8082