spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jngvarr/SalonConfig.git
          default-label: main
server:
  port: 8888
  #          basedir: c:\..\gb\springConfig\
#          basedir: .\gb\salonConfig\
#        native: ???????? ??? ?????????? ???????????? ????????? ??? ?? ??? ? instance.spring cloud.config
#          search-locations: file://${user.home}/C:/Users/jngva/gb/Beauty-salon/config #??? ?????? ????? ????????????
