server:
  port: 8082
spring:
  security:
    user:
      name: user
      password: pass
  config:
    import:
      configserver:http://localhost:8888
  application:
    name: services

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
#        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://62.76.142.52:5432/salondb
    username: user
    password: passw
    hikari:
      schema: salon
      maximum-pool-size: 2
      minimum-idle: 5
  sql:
    init:
      mode: always

logging:
  level:
    ru.jngvarr: DEBUG
#    org.springframework.security: TRACE


