server:
  port: 8089
spring:
  config:
    import:
      configserver:http://localhost:8888
  application:
    name: security

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://62.76.142.52:5432/salondb
    username: user
    password: passw
    hikari:
      schema: salon
      maximum-pool-size: 2
      minimum-idle: 5
  sql:
    init:
      mode: always

logging:
  level:
    ru.jngvarr: DEBUG
#    org.springframework.security: TRACE
#feign:
#  client:
#    config:
#      clients:
#        basic-auth:
#          username: user or salonUser
#          password: pass