package jngvarr.ru;

public enum OTOWorkTypes {
    METER_REPLACING,
    DC_REPLACING,
    DC_CHANGING,
    TT_REPLACING,
    DROP_WK,
    METER_SCHEME_RESTORATION,
    DC_SCHEME_RESTORATION,
    IIK_STATUS_CHANGING,


}
